// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgPdEhIIEoQADZT_5d2ysk_1mr18AJmM',
    appId: '1:470598196720:web:4db87864b522f23d0d9135',
    messagingSenderId: '470598196720',
    projectId: 'wiigold-wallet-staging',
    authDomain: 'wiigold-wallet-staging.firebaseapp.com',
    storageBucket: 'wiigold-wallet-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD9DQqBCCaeYRWsFuXE-IEV9LSyjYCC0o',
    appId: '1:470598196720:android:5827a000d888d8c20d9135',
    messagingSenderId: '470598196720',
    projectId: 'wiigold-wallet-staging',
    storageBucket: 'wiigold-wallet-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9i_xoqDQ35DwdqgDzg7PUnHSUIRmNbCw',
    appId: '1:470598196720:ios:d16c711af413e5540d9135',
    messagingSenderId: '470598196720',
    projectId: 'wiigold-wallet-staging',
    storageBucket: 'wiigold-wallet-staging.firebasestorage.app',
    iosBundleId: 'com.wiigold.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9i_xoqDQ35DwdqgDzg7PUnHSUIRmNbCw',
    appId: '1:470598196720:ios:d16c711af413e5540d9135',
    messagingSenderId: '470598196720',
    projectId: 'wiigold-wallet-staging',
    storageBucket: 'wiigold-wallet-staging.firebasestorage.app',
    iosBundleId: 'com.wiigold.wallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqgPdEhIIEoQADZT_5d2ysk_1mr18AJmM',
    appId: '1:470598196720:web:74630d44cbc03a400d9135',
    messagingSenderId: '470598196720',
    projectId: 'wiigold-wallet-staging',
    authDomain: 'wiigold-wallet-staging.firebaseapp.com',
    storageBucket: 'wiigold-wallet-staging.firebasestorage.app',
  );
}
