class Bank {
  final String bankName;
  final String swiftCode;

  Bank({required this.bankName, required this.swiftCode});
}

Bank? getBankBySwiftCode(String swiftCode) {
  try {
    return banks.firstWhere((bank) => bank.swiftCode == swiftCode);
  } on StateError {
    return null;
  }
}

final List<Bank> banks = [
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33XXX"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3NXXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SXXX"),
  Bank(bankName: "CITIBANK, N.A.", swiftCode: "CITIUS33XXX"),
  Bank(bankName: "U.S. BANK N.A.", swiftCode: "USBKUS44XXX"),
  Bank(bankName: "PNC BANK, N.A.", swiftCode: "PNCCUS33XXX"),
  Bank(bankName: "TRUIST BANK", swiftCode: "SUNTUS33XXX"),
  Bank(bankName: "CAPITAL ONE, N.A.", swiftCode: "COINUS33XXX"),
  Bank(bankName: "TD BANK, N.A.", swiftCode: "TDOMUS33XXX"),
  Bank(bankName: "FIRST CITIZENS BANK", swiftCode: "FCIBUS33XXX"),
  Bank(bankName: "1ST ENTERPRISE BANK", swiftCode: "FEBKUS6LXXX"),
  Bank(bankName: "1ST UNITED BANK", swiftCode: "HEMSUS3MXXX"),
  Bank(bankName: "ABACUS FEDERAL SAVINGS BANK", swiftCode: "AFSBUS33XXX"),
  Bank(bankName: "ABBEY NATIONAL SECURITIES INC.", swiftCode: "ANSSUS33XXX"),
  Bank(
    bankName: "ABBEY NATIONAL TREASURY SERVICES LTD US BRANCH",
    swiftCode: "ANTSUS33XXX",
  ),
  Bank(bankName: "ABERCROMBIE AND FITCH CO.", swiftCode: "ANFCUS33XXX"),
  Bank(bankName: "ABN AMRO CAPITAL USA LLC", swiftCode: "FTSBUS33XXX"),
  Bank(bankName: "ABU DHABI INTERNATIONAL BANK INC.", swiftCode: "ADIBUS33XXX"),
  Bank(bankName: "ACADEMY BANK, N.A.", swiftCode: "ACAYUS41XXX"),
  Bank(bankName: "ACI CAPITAL GROUP, LLC", swiftCode: "ACIXUS33XXX"),
  Bank(bankName: "ACUPAY SYSTEM LLC", swiftCode: "ACPYUS33XXX"),
  Bank(
    bankName: "ADP CLEARING AND OUTSOURCING SERVICES INC.",
    swiftCode: "ADPCUS33XXX",
  ),
  Bank(bankName: "ADP GLOBAL PROXY SERVICES", swiftCode: "ADPGUS33XXX"),
  Bank(
    bankName: "AEGON USA INVESTMENT MANAGEMENT, LLC",
    swiftCode: "AEGUUS44XXX",
  ),
  Bank(bankName: "AGILENT TECHNOLOGIES, INC", swiftCode: "AGILUS6SXXX"),
  Bank(
    bankName: "AGRICULTURAL BANK OF CHINA NEW YORK BRANCH",
    swiftCode: "ABOCUS33XXX",
  ),
  Bank(bankName: "AIB BANK", swiftCode: "AIBKUS3TTMK"),
  Bank(bankName: "AIB BANK", swiftCode: "AIBKUS33XXX"),
  Bank(bankName: "AIB BANK", swiftCode: "AIBKUS3TXXX"),
  Bank(bankName: "AIG FINANCIAL PRODUCTS CORP.", swiftCode: "AIGFUS33XXX"),
  Bank(bankName: "AIG INTERNATIONAL INC.", swiftCode: "AIGIUS33XXX"),
  Bank(bankName: "ALCOA INC.", swiftCode: "ALUMUS33XXX"),
  Bank(bankName: "ALLY FINANCIAL INC", swiftCode: "ALYIUS33INC"),
  Bank(bankName: "ALLY FINANCIAL INC", swiftCode: "ALYIUS33QTM"),
  Bank(bankName: "ALLY FINANCIAL INC", swiftCode: "ALYIUS33SER"),
  Bank(bankName: "ALLY FINANCIAL INC", swiftCode: "ALYIUS33XXX"),
  Bank(bankName: "ALOSTAR BANK OF COMMERCE", swiftCode: "ALOEUS44XXX"),
  Bank(bankName: "ALTICOR INC", swiftCode: "AMWYUS33XXX"),
  Bank(bankName: "AMAZON CORPORATE LLC", swiftCode: "ACOLUS66XXX"),
  Bank(bankName: "AMB PROPERTY, L.P.", swiftCode: "AMBCUS6LXXX"),
  Bank(bankName: "AMEGY BANK N.A.", swiftCode: "SWBKUS44XXX"),
  Bank(bankName: "AMERICAN BUSINESS BANK", swiftCode: "ACBBUS6LXXX"),
  Bank(
    bankName: "AMERICAN EXPRESS TRAVEL RELATED SERVICES COMPANY, INC.",
    swiftCode: "AETCUS33XXX",
  ),
  Bank(
    bankName: "AMERICAN EXPRESS TRAVEL RELATED SERVICES COMPANY, INC.",
    swiftCode: "AETCUS3AXXX",
  ),
  Bank(
    bankName: "AMERICAN EXPRESS TRAVEL RELATED SERVICES COMPANY, INC.",
    swiftCode: "AETCUS3BXXX",
  ),
  Bank(
    bankName: "AMERICAN EXPRESS TRAVEL RELATED SERVICES CO., INC.",
    swiftCode: "AETCUS55XXX",
  ),
  Bank(bankName: "AMERICAN FIRST NATIONAL BANK", swiftCode: "AFNBUS4HXXX"),
  Bank(bankName: "AMERICAN INTERNATIONAL GROUP", swiftCode: "AIGXUS33XXX"),
  Bank(
    bankName: "AMERICAN INTERNATIONAL GROUP GLOBAL INVESTMENT GROUP",
    swiftCode: "AGIGUS3WXXX",
  ),
  Bank(
    bankName: "AMERICAN INTERNATIONAL GROUP GLOBAL INVESTMENT GROUP",
    swiftCode: "AGIGUS33XXX",
  ),
  Bank(
    bankName: "AMERICAN INTERNATIONAL GROUP GLOBAL INVESTMENT GROUP",
    swiftCode: "AGIGUS33MKT",
  ),
  Bank(bankName: "AMERICAN PERSPECTIVE BANK", swiftCode: "APBAUS6LXXX"),
  Bank(bankName: "ANNALY CAPITAL MANAGEMENT, INC.", swiftCode: "ANCGUS33XXX"),
  Bank(bankName: "APOLLO BANK", swiftCode: "UCBMUS3MXXX"),
  Bank(bankName: "ARAB BANKING CORPORATION", swiftCode: "ABCOUS33XXX"),
  Bank(bankName: "ARES MANAGEMENT LLC", swiftCode: "ARNLUS66XXX"),
  Bank(
    bankName: "ARNOLD AND S. BLEICHROEDER ADVISORS, LLC",
    swiftCode: "AAMSUS31XXX",
  ),
  Bank(bankName: "ARVEST BANK", swiftCode: "ARVTUS44XXX"),
  Bank(bankName: "ASSOCIATED BANK, N.A.", swiftCode: "ABGBUS44XXX"),
  Bank(bankName: "ASSOCIATED FOREIGN EXCHANGE, INC", swiftCode: "AFEIUS6LXXX"),
  Bank(bankName: "ATLANTIC CENTRAL BANKERS BANK", swiftCode: "ATLCUS33XXX"),
  Bank(
    bankName: "AUSTRALIA AND NEW ZEALAND BANKING GROUP LTD.",
    swiftCode: "ANZBUS33XXX",
  ),
  Bank(
    bankName: "AVENUE CAPITAL MANAGEMENT II, L.P.",
    swiftCode: "ACLMUS32XXX",
  ),
  Bank(bankName: "AVERY DENNISON CORPORATION", swiftCode: "AVERUS66XXX"),
  Bank(bankName: "AVM L.P.", swiftCode: "IIIAUS33XXX"),
  Bank(bankName: "BAC FLORIDA BANK", swiftCode: "BFLBUS3MXXX"),
  Bank(bankName: "BAIN AND COMPANY INC", swiftCode: "BAOYUS33XXX"),
  Bank(bankName: "BAKER HUGHES INCORPORATED", swiftCode: "BHICUS44XXX"),
  Bank(bankName: "BALYASNY ASSET MANAGEMENT L.P.", swiftCode: "BLAGUS44XXX"),
  Bank(bankName: "BANAMEX USA", swiftCode: "CALCUS6LXXX"),
  Bank(bankName: "BANCA IMI SECURITIES CORP.", swiftCode: "BIMIUS33XXX"),
  Bank(bankName: "BANCFIRST", swiftCode: "BFOKUS44XXX"),
  Bank(
    bankName: "BANCO BILBAO VIZCAYA ARGENTARIA, NEW YORK",
    swiftCode: "BBVAUS33GCI",
  ),
  Bank(
    bankName: "BANCO BILBAO VIZCAYA ARGENTARIA, NEW YORK",
    swiftCode: "BBVAUS33IBF",
  ),
  Bank(
    bankName: "BANCO BILBAO VIZCAYA ARGENTARIA, NEW YORK",
    swiftCode: "BBVAUS33XXX",
  ),
  Bank(bankName: "BBVA SECURITIES INC.", swiftCode: "BBVAUS3SXXX"),
  Bank(bankName: "BANCO BRADESCO S.A.", swiftCode: "BBDEUS33XXX"),
  Bank(bankName: "BANCO DAVIVIENDA S.A.", swiftCode: "CAFEUS3MXXX"),
  Bank(bankName: "BANCO DE BOGOTA, MIAMI AGENCY", swiftCode: "BBOGUS3MXXX"),
  Bank(
    bankName: "BANCO DE CREDITO DEL PERU - MIAMI AGENCY",
    swiftCode: "BCPLUS33XXX",
  ),
  Bank(
    bankName: "BANCO DE CREDITO E INVERSIONES, MIAMI BRANCH",
    swiftCode: "CREDUS3MXXX",
  ),
  Bank(bankName: "BANCO DE LA NACION ARGENTINA", swiftCode: "NACNUS33XXX"),
  Bank(
    bankName: "BANCO DE LA NACION ARGENTINA, MIAMI BRANCH",
    swiftCode: "NACNUS3MXXX",
  ),
  Bank(
    bankName: "BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY",
    swiftCode: "BROUUS33XXX",
  ),
  Bank(bankName: "BANCO DE SABADELL, S.A.", swiftCode: "BSABUS3XXXX"),
  Bank(
    bankName: "BANCO DEL PICHINCHA - MIAMI AGENCY",
    swiftCode: "PICHUS3MXXX",
  ),
  Bank(bankName: "BANCO DO BRASIL S.A", swiftCode: "BRASUS3MXXX"),
  Bank(bankName: "BANCO DO BRASIL S.A", swiftCode: "BRASUS33XXX"),
  Bank(
    bankName: "BANCO DO ESTADO DO RIO GRANDE DO SUL-MIAMI BRANCH",
    swiftCode: "BRGSUS33XXX",
  ),
  Bank(bankName: "BANCO ESPANOL DE CREDITO", swiftCode: "ESPCUS3NXXX"),
  Bank(bankName: "BANCO ESPIRITO SANTO", swiftCode: "BESCUS33XXX"),
  Bank(
    bankName: "BANCO ESPIRITO SANTO DE INVESTIMENTO, S.A.",
    swiftCode: "ESSIUS3NXXX",
  ),
  Bank(
    bankName: "BANCO ESTADO DE CHILE NEW YORK BRANCH.",
    swiftCode: "BECHUS33XXX",
  ),
  Bank(bankName: "BANCO INDUSTRIAL DE VENEZUELA", swiftCode: "INDSUS33XXX"),
  Bank(
    bankName: "BANCO INDUSTRIAL DE VENEZUELA, C.A. MIAMI AGENCY",
    swiftCode: "INDSUS3MXXX",
  ),
  Bank(
    bankName: "BANCO INTERNACIONAL DE COSTA RICA, MIAMI AGENCY",
    swiftCode: "COSRUS3MXXX",
  ),
  Bank(bankName: "BANCO ITAU EUROPA INTERNATIONAL", swiftCode: "ITAUUS3MXXX"),
  Bank(
    bankName: "BANCO LATINOAMERICANO DE COMERCIO EXTERIOR S.A.",
    swiftCode: "BLAEUS3XXXX",
  ),
  Bank(bankName: "BANCO SANTANDER INTERNATIONAL", swiftCode: "BDERUS3MXXX"),
  Bank(bankName: "BANCO SANTANDER S.A. NEW YORK", swiftCode: "BSCHUS33XXX"),
  Bank(bankName: "BANCOLOMBIA S.A. MIAMI AGENCY", swiftCode: "COLOUS33XXX"),
  Bank(bankName: "BANCOMER TRANSFER SERVICES INC.", swiftCode: "BTSIUS44BFX"),
  Bank(bankName: "BANCOMER TRANSFER SERVICES INC.", swiftCode: "BTSIUS44BTS"),
  Bank(bankName: "BANCOMER TRANSFER SERVICES INC.", swiftCode: "BTSIUS44XXX"),
  Bank(bankName: "BANESCO USA", swiftCode: "BBUBUS33XXX"),
  Bank(
    bankName: "BANGKOK BANK PUBLIC COMPANY LIMITED, NEW YORK",
    swiftCode: "BKKBUS33XXX",
  ),
  Bank(bankName: "BANGOR SAVINGS BANK", swiftCode: "BSMEUS33XXX"),
  Bank(bankName: "BANK HAPOALIM B.M.", swiftCode: "POALUS33CHG"),
  Bank(bankName: "BANK HAPOALIM B.M.", swiftCode: "POALUS33MIA"),
  Bank(bankName: "BANK HAPOALIM B.M.", swiftCode: "POALUS33XXX"),
  Bank(bankName: "BANK HAPOALIM B.M.", swiftCode: "POALUS33GTN"),
  Bank(bankName: "BANK LEUMI USA", swiftCode: "LUMIUS3NCHI"),
  Bank(bankName: "BANK LEUMI USA", swiftCode: "LUMIUS3NLAX"),
  Bank(bankName: "BANK LEUMI USA", swiftCode: "LUMIUS3NMIA"),
  Bank(bankName: "BANK LEUMI USA", swiftCode: "LUMIUS3NXXX"),
  Bank(
    bankName: "BANK NEGARA INDONESIA (PERSERO) PT., NEW YORK AGENCY",
    swiftCode: "BNINUS33XXX",
  ),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DAU2"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DSG3"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DSG2"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DAUS"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DDOC"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DEQN"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DFIA"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DMET"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DPLX"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3DXXX"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3MXXX"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3NATS"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3NINQ"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3NLMA"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3NLTS"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS3NTRS"),
  Bank(bankName: "BANK OF AMERICA, N.A.", swiftCode: "BOFAUS6BXXX"),
  Bank(
    bankName: "BANK OF EAST ASIA LIMITED, THE, NEW YORK BRANCH",
    swiftCode: "BEASUS33XXX",
  ),
  Bank(
    bankName: "BLACKROCK FINANCIAL MANAGEMENT INC.",
    swiftCode: "BLKSUS33XXX",
  ),
  Bank(
    bankName: "BLACKROCK FINANCIAL MANAGEMENT INC.",
    swiftCode: "BLKSUS3AXXX",
  ),
  Bank(
    bankName: "BLACKROCK FINANCIAL MANAGEMENT INC.",
    swiftCode: "BLKSUS3BXXX",
  ),
  Bank(bankName: "BROWN BROTHERS HARRIMAN AND CO.", swiftCode: "BBHCUS33BOS"),
  Bank(bankName: "CAPITAL ONE, N.A.", swiftCode: "COINUS33XXX"),
  Bank(bankName: "CHARLES SCHWAB AND CO INC.", swiftCode: "CSCHUS66XXX"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6SGLB"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6SIMO"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6SINT"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6SPFF"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6SPFX"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6STMO"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6STRE"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6SWTS"),
  Bank(bankName: "CHARLES SCHWAB AND CO., INC.", swiftCode: "CSCHUS6SXXX"),
  Bank(bankName: "CITIBANK, N.A.", swiftCode: "CITIUS33XXX"),
  Bank(bankName: "COMERICA BANK", swiftCode: "MNBDUS33XXX"),
  Bank(
    bankName: "DELTA NATIONAL BANK AND TRUST CO. OF NEW YORK",
    swiftCode: "DNBTUS33XXX",
  ),
  Bank(
    bankName: "DAIWA CAPITAL MARKETS AMERICA INC.",
    swiftCode: "DSANUS3NXXX",
  ),
  Bank(bankName: "EIDP, INC.", swiftCode: "DUPTUS33XXX"),
  Bank(bankName: "EIDP, INC.", swiftCode: "DUPTUS3AXXX"),
  Bank(bankName: "ECS FIN INC.", swiftCode: "ECSNUS33NCA"),
  Bank(bankName: "EVERBANK, N.A.", swiftCode: "EVBKUS3MXXX"),
  Bank(bankName: "EVERCORE GROUP L.L.C.", swiftCode: "EVGCUS31XXX"),
  Bank(bankName: "FIDELITY SERVICE COMPANY, INC.", swiftCode: "FIDQUS33XXX"),
  Bank(bankName: "FIDELITY SERVICE COMPANY, INC.", swiftCode: "FIDQUS3AXXX"),
  Bank(bankName: "FIDELITY SERVICE COMPANY, INC.", swiftCode: "FIDQUS3BXXX"),
  Bank(bankName: "FIFTH THIRD BANK, N.A.", swiftCode: "FTBCUS3CXXX"),
  Bank(bankName: "FIRST CITIZENS BANK", swiftCode: "FCIBUS33XXX"),
  Bank(
    bankName: "FLAGSTAR BANK, N.A. (FORMERLY NEW YORK COMMUNITY BANK)",
    swiftCode: "ABNYUS33XXX",
  ),
  Bank(bankName: "HSBC BANK USA, N.A.", swiftCode: "MRMDUS33XXX"),
  Bank(bankName: "HUNTINGTON NATIONAL BANK, THE", swiftCode: "HUNTUS33XXX"),
  Bank(bankName: "INTERCREDIT BANK N.A.", swiftCode: "BBITUS3MXXX"),
  Bank(bankName: "J.P. MORGAN SECURITIES LLC", swiftCode: "BEARUS33XXX"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33XXX"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33CFC"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33CON"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33GAD"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33GTC"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33MAE"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OB1"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OC1"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OC2"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OC3"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OG1"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OU1"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OU2"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OU3"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OUB"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33OUG"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33RMB"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33SBD"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33SGC"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33SIM"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33UBD"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33UCO"),
  Bank(bankName: "JPMORGAN CHASE BANK, N.A.", swiftCode: "CHASUS33UGC"),
  Bank(bankName: "KEYBANK NATIONAL ASSOCIATION", swiftCode: "KEYBUS33XXX"),
  Bank(bankName: "M&T BANK", swiftCode: "MNTBUS33XXX"),
  Bank(bankName: "NATWEST MARKETS SECURITIES INC.", swiftCode: "RBOSUS3GXXX"),
  Bank(bankName: "PAYPAL INC.", swiftCode: "PPALUS66XXX"),
  Bank(bankName: "PNC BANK, N.A.", swiftCode: "PNCCUS33XXX"),
  Bank(bankName: "PNC BANK, N.A.", swiftCode: "PNCCUS31CMG"),
  Bank(bankName: "PNC BANK, N.A.", swiftCode: "PNCCUS31FXO"),
  Bank(bankName: "PNC BANK, N.A.", swiftCode: "PNCCUS33ENJ"),
  Bank(bankName: "PNC BANK, N.A.", swiftCode: "PNCCUS3CXXX"),
  Bank(bankName: "PPM AMERICA INC.", swiftCode: "PPAEUS44XXX"),
  Bank(
    bankName: "RBC BANK (GEORGIA), NATIONAL ASSOC.",
    swiftCode: "RBCBUS33XXX",
  ),
  Bank(bankName: "RAFFERTY CAPITAL MARKETS, LLC", swiftCode: "RCALUS31XXX"),
  Bank(bankName: "REGIONS BANK", swiftCode: "REGNUS44XXX"),
  Bank(
    bankName: "REINSURANCE GROUP OF AMERICA, INC.",
    swiftCode: "RGARUS44XXX",
  ),
  Bank(
    bankName: "REINSURANCE GROUP OF AMERICA, INC.",
    swiftCode: "RGARUS4AXXX",
  ),
  Bank(bankName: "REVOLUT TECHNOLOGIES INC.", swiftCode: "REVOUS31XXX"),
  Bank(bankName: "SANTANDER BANK, N.A.", swiftCode: "SVRNUS33XXX"),
  Bank(
    bankName: "SOUTH STATE BANK, N.A. (FORMERLY CENTERSTATE BANK,N.A.)",
    swiftCode: "CSBKUS33XXX",
  ),
  Bank(
    bankName: "STATE STREET BANK AND TRUST COMPANY",
    swiftCode: "IRVTUS3NXXX",
  ),
  Bank(bankName: "SUNTRUST BANK", swiftCode: "SUNTUS33XXX"),
  Bank(bankName: "TD BANK, N.A.", swiftCode: "TDOMUS33XXX"),
  Bank(bankName: "THE BANK OF NEW YORK MELLON", swiftCode: "IRVTUS3NXXX"),
  Bank(bankName: "TRUIST BANK", swiftCode: "SUNTUS33XXX"),
  Bank(bankName: "U.S. BANK N.A.", swiftCode: "USBKUS44XXX"),
  Bank(bankName: "USAA FEDERAL SAVINGS BANK", swiftCode: "USAAFUS44XXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SXXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6AXXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6BXXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SANC"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SBOI"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SCHI"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SCTS"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SDAL"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SDEN"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SDES"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SELP"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SENG"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SGOL"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SHOU"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SLAS"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SLAX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SLIN"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SMSP"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SOMA"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SPDX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SPHX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SRNO"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SSEA"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SSFE"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SSFO"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "WFBIUS6SSLC"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS33CHA"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS33FMG"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS33PHL"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS33SLC"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS33XXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS33ZIA"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS3CXXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS3MXXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS3NNYC"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS3NXXX"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS3NZIA"),
  Bank(bankName: "WELLS FARGO BANK, N.A.", swiftCode: "PNBPUS6LXXX"),
  Bank(bankName: "ZIONS BANCORPORATION, N.A.", swiftCode: "ZIORUS44XXX"),
  Bank(bankName: "AMERICAN SAVINGS BANK", swiftCode: "ASBKHIUS33XXX"),
  Bank(bankName: "SYNOVUS BANK", swiftCode: "SYNVUS33XXX"),
  Bank(bankName: "POPULAR BANK", swiftCode: "POPBUS33XXX"),
  Bank(bankName: "EASTERN BANK", swiftCode: "EBNKUS33XXX"),
  Bank(bankName: "FIRST HAWAIIAN BANK", swiftCode: "FHBKUS77XXX"),
  Bank(bankName: "PACIFIC PREMIER BANK", swiftCode: "PPBIUS33XXX"),
  Bank(bankName: "CATHAY BANK", swiftCode: "CATBUS6LXXX"),
  Bank(bankName: "CITIZENS BANK", swiftCode: "CTZNUS33XXX"),
  Bank(bankName: "FIRST INTERSTATE BANK", swiftCode: "FIBKUS44XXX"),
  Bank(bankName: "TEXAS CAPITAL BANK", swiftCode: "TXCBUS44XXX"),
  Bank(bankName: "WEST BANK", swiftCode: "WSTBUS44XXX"),
  Bank(bankName: "GLACIER BANK", swiftCode: "GLCRUS44XXX"),
  Bank(bankName: "PINNACLE BANK", swiftCode: "PNCLUS44XXX"),
  Bank(bankName: "FIRST NATIONAL BANK OF OMAHA", swiftCode: "FNBOUS44XXX"),
  Bank(bankName: "WASHINGTON FEDERAL", swiftCode: "WFEDUS6SXXX"),
  Bank(bankName: "STOCK YARDS BANK & TRUST CO.", swiftCode: "SYBKUS44XXX"),
  Bank(bankName: "LIBERTY BANK", swiftCode: "LBTYUS33XXX"),
  Bank(bankName: "GREAT WESTERN BANK", swiftCode: "GWBKUS44XXX"),
  Bank(bankName: "FIRST MERCHANTS BANK", swiftCode: "FMCBUS44XXX"),
  Bank(bankName: "COLUMBIA BANK", swiftCode: "CLMBRUS44XXX"),
  Bank(bankName: "SIMMONS BANK", swiftCode: "SMMNUS44XXX"),
  Bank(bankName: "RENASANT BANK", swiftCode: "RNSTUS44XXX"),
  Bank(bankName: "TRUSTMARK NATIONAL BANK", swiftCode: "TRMKUS44XXX"),
  Bank(bankName: "CADENCE BANK", swiftCode: "CDNCUS44XXX"),
  Bank(bankName: "SPIRIT OF TEXAS BANCSHARES", swiftCode: "SPTXUS44XXX"),
  Bank(bankName: "COMMUNITY TRUST BANK", swiftCode: "CMTYUS44XXX"),
  Bank(bankName: "OLD NATIONAL BANK", swiftCode: "OLDNUS44XXX"),
  Bank(bankName: "SECURITY BANK", swiftCode: "SCTYUS44XXX"),
  Bank(bankName: "MIDLAND STATES BANK", swiftCode: "MDLBUS44XXX"),
  Bank(bankName: "MERIDIAN BANK", swiftCode: "MRDNUS33XXX"),
  Bank(bankName: "ENTERPRISE BANK & TRUST", swiftCode: "ENTRUS44XXX"),
  Bank(bankName: "PROSPERITY BANK", swiftCode: "PRSPUS44XXX"),
  Bank(bankName: "TEXAS REGIONAL BANK", swiftCode: "TXRGUS44XXX"),
  Bank(bankName: "CENTRAL PACIFIC BANK", swiftCode: "CEPBHIUS33XXX"),
  Bank(bankName: "INTERNATIONAL BANK OF COMMERCE", swiftCode: "IBOCUS44XXX"),
  Bank(bankName: "SOUTHERN FIRST BANK", swiftCode: "SFSTUS33XXX"),
  Bank(bankName: "CARTER BANK & TRUST", swiftCode: "CBATUS33XXX"),
  Bank(bankName: "FIRST SECURITY BANK", swiftCode: "FSBKUS44XXX"),
  Bank(bankName: "COMMUNITY BANK SYSTEM", swiftCode: "CBSNUS33XXX"),
  Bank(bankName: "INDEPENDENT BANK", swiftCode: "INDBUS44XXX"),
  Bank(bankName: "LAKELAND FINANCIAL", swiftCode: "LKLDUS44XXX"),
  Bank(bankName: "FIRST FINANCIAL BANK", swiftCode: "FFBCUS33XXX"),
  Bank(bankName: "PARK NATIONAL BANK", swiftCode: "PRKNBUS44XXX"),
  Bank(bankName: "CHEMUNG CANAL TRUST COMPANY", swiftCode: "CHCTUS33XXX"),
  Bank(bankName: "FIRST FINANCIAL BANKSHARES", swiftCode: "FFINUS44XXX"),
  Bank(bankName: "FARMERS & MERCHANTS BANK", swiftCode: "FMBCUS6LXXX"),
  Bank(bankName: "PACIFIC CITY BANK", swiftCode: "PCIBUS6LXXX"),
  Bank(bankName: "EASTERN NATIONAL BANK", swiftCode: "ETNBUS3MXXX"),
  Bank(
    bankName: "FIRST NATIONAL BANK OF PENNSYLVANIA",
    swiftCode: "FNBPUS33XXX",
  ),
  Bank(bankName: "FIRST FINANCIAL NORTHWEST", swiftCode: "FFNWUS6SXXX"),
  Bank(bankName: "NORTHERN TRUST CORPORATION", swiftCode: "CNORUS44XXX"),
  Bank(bankName: "BANCORP BANK", swiftCode: "TBBKUS33XXX"),
  Bank(bankName: "MORGAN STANLEY BANK", swiftCode: "MSBNUS44XXX"),
  Bank(bankName: "GOLDMAN SACHS BANK USA", swiftCode: "GSBLUS33XXX"),
  Bank(bankName: "SYNCHRONY BANK", swiftCode: "SYNCUS44XXX"),
  Bank(bankName: "ALLY FINANCIAL INC", swiftCode: "ALYIUS33XXX"),
  Bank(bankName: "SYNCHRONY BANK", swiftCode: "SYNCUS44XXX"),
  Bank(bankName: "GOLDMAN SACHS BANK USA", swiftCode: "GSBLUS33XXX"),

  Bank(bankName: "BANCOLOMBIA S.A.", swiftCode: "COLOCOBM"),
  Bank(bankName: "BANCO DE BOGOTÁ", swiftCode: "BBOGCOBB"),
  Bank(bankName: "BANCO DAVIVIENDA S.A.", swiftCode: "CAVDCOBB"),
  Bank(
    bankName: "BANCO BILBAO VIZCAYA ARGENTARIA COLOMBIA S.A.",
    swiftCode: "GEROCOBB",
  ),
  Bank(bankName: "BANCO DE OCCIDENTE S.A.", swiftCode: "OCCICOBC"),
  Bank(bankName: "BANCO POPULAR S.A.", swiftCode: "BPOPCOBB"),
  Bank(bankName: "BANCO CAJA SOCIAL", swiftCode: "CASOCOBB"),
  Bank(bankName: "BANCO COLPATRIA", swiftCode: "COLPCOBB"),
  Bank(bankName: "BANCO GNB SUDAMERIS", swiftCode: "BSUDCOBB"),
  Bank(bankName: "BANCO SANTANDER COLOMBIA S.A.", swiftCode: "BSCHCOBB"),
  Bank(
    bankName:
        "ADMINISTRADORA DE FONDOS DE PENSIONES Y CESANTIA PROTECCION S.A.",
    swiftCode: "PROPCOBM",
  ),
  Bank(bankName: "BANCO AGRARIO DE COLOMBIA S.A.", swiftCode: "CCAICOBB"),
  Bank(bankName: "BANCO AV VILLAS S.A.", swiftCode: "BAVICOBB"),
  Bank(bankName: "BANCO DAVIVIENDA S.A.", swiftCode: "CAFECOBB"),
  Bank(bankName: "BANCO DE BOGOTÁ", swiftCode: "BBOGCOBS"),
  Bank(
    bankName: "BANCO DE COMERCIO EXTERIOR S.A. - BANCOLDEX",
    swiftCode: "BCEXCOBB",
  ),
  Bank(bankName: "BANCO DE CREDITO", swiftCode: "BCTOCOBB"),
  Bank(bankName: "BANCO DE LA REPUBLICA", swiftCode: "BREPCOBB"),
  Bank(bankName: "BANCO DE OCCIDENTE S.A.", swiftCode: "OCCICOBS"),
  Bank(bankName: "BANCO POPULAR S.A.", swiftCode: "BPOPCOBS"),
  Bank(bankName: "BANCO PROCREDIT COLOMBIA S.A.", swiftCode: "PRCBCOBB"),
  Bank(bankName: "BANCO SANTANDER COLOMBIA S.A.", swiftCode: "BSCHCOBC"),
  Bank(bankName: "BANCOLOMBIA S.A.", swiftCode: "COLOCOBP"),
  Bank(bankName: "BANCOLOMBIA S.A.", swiftCode: "COLOCOBB"),
  Bank(bankName: "CITIBANK COLOMBIA", swiftCode: "CITICOBB"),
  Bank(
    bankName: "CÁMARA DE COMPENSACIÓN DE DIVISAS DE COLOMBIA S.A.",
    swiftCode: "CCDCCOBB",
  ),
  Bank(
    bankName: "COLTEFINANCIERA S.A. COMPAÑÍA DE FINANCIAMIENTO COMERCIAL",
    swiftCode: "CLTECOBM",
  ),
  Bank(bankName: "CORPORACIÓN FINANCIERA COLOMBIANA", swiftCode: "CFVACOBC"),
  Bank(bankName: "CORREVAL S.A.", swiftCode: "CRVLCOBB"),
  Bank(bankName: "HELM BANK S.A.", swiftCode: "HELGCOBB"),
  Bank(bankName: "HSBC COLOMBIA S.A.", swiftCode: "HSBCCOBB"),
  Bank(bankName: "ITAU CORPBANCA COLOMBIA S.A.", swiftCode: "ITAUCOBB"),
  Bank(bankName: "SCOTIA BANK COLOMBIA S.A.", swiftCode: "NOSCCOBBXXX"),
  Bank(bankName: "BANCAMIA S.A.", swiftCode: "BCAMCOBB"),
  Bank(bankName: "BANCO CREDIFINANCIERA S.A.", swiftCode: "CRFICOBM"),
  Bank(bankName: "BANCO FINANDINA S.A.", swiftCode: "FINDCOBB"),
  Bank(bankName: "BANCO PICHINCHA S.A.", swiftCode: "PICHCOBB"),
  Bank(bankName: "BANCO W S.A.", swiftCode: "BANCWCOBB"),
  Bank(bankName: "BANCO SERFINANZA S.A.", swiftCode: "SERFCOBM"),
  Bank(bankName: "BANCO MUNDO MUJER S.A.", swiftCode: "MUNDCOBB"),
  Bank(bankName: "MIBANCO S.A.", swiftCode: "MIBACOBM"),
  Bank(
    bankName: "BANCO DE LAS MICROFINANZAS - BANCAMÍA S.A.",
    swiftCode: "BCAMCOBB",
  ),
  Bank(
    bankName: "LEASING BANCOLOMBIA S.A. COMPAÑÍA DE FINANCIAMIENTO COMERCIAL",
    swiftCode: "LEASCOBC",
  ),
  Bank(
    bankName: "GM FINANCIAL COLOMBIA COMPAÑÍA DE FINANCIAMIENTO S.A.",
    swiftCode: "GMFCCOBB",
  ),
  Bank(bankName: "BANCO COOPERATIVO COOPCENTRAL", swiftCode: "COOPCOBB"),
  Bank(bankName: "BANCO FALABELLA S.A.", swiftCode: "FALACOBB"),
  Bank(bankName: "NEQUI S.A.", swiftCode: "NEQUCOBM"),
  Bank(bankName: "BANCO JPMorgan COLOMBIA S.A.", swiftCode: "JPMOCOBB"),
  Bank(bankName: "LULO BANK S.A.", swiftCode: "LULOCOBB"),
  Bank(bankName: "RAPPIPAY S.A.", swiftCode: "RAPPCOBBXXX"),
];
