import 'package:get/get.dart';

class AppErrors {
  static const Map<String, dynamic> knownErrors = {
    //? Auth / Generic
    "AUTH0_EMAIL_ALREADY_REGISTERED": 'errors.AUTH0_EMAIL_ALREADY_REGISTERED',
    "AUTH0_EMAIL_UPDATED_ERROR": 'errors.AUTH0_EMAIL_UPDATED_ERROR',
    "AUTH0_ERROR_REGISTERING_USER": 'errors.AUTH0_ERROR_REGISTERING_USER',
    "AUTH_DATA_UPDATE_ERROR": 'errors.AUTH_DATA_UPDATE_ERROR',
    "AUTH_USER_NOT_FOUND": 'errors.AUTH_USER_NOT_FOUND',
    "CONNECTION_ERROR": 'errors.CONNECTION_ERROR',
    "EMAIL_UNAVAILABLE": 'errors.EMAIL_UNAVAILABLE',
    "EMAIL_UNAVAILABLE_LOGIN": 'errors.EMAIL_UNAVAILABLE_LOGIN',
    "EMAIL_UNAVAILABLE_REGISTER": 'errors.EMAIL_UNAVAILABLE_REGISTER',
    "ERROR_CHECK_EMAIL": 'errors.ERROR_CHECK_EMAIL',
    "ERROR_DELETING_USER": 'errors.ERROR_DELETING_USER',
    "ERROR_REGISTERING_USER": 'errors.ERROR_REGISTERING_USER',
    "INVALID_CHECK_EMAIL_DATA": 'errors.INVALID_CHECK_EMAIL_DATA',
    "INVALID_DELETE_ACTION": 'errors.INVALID_DELETE_ACTION',
    "INVALID_DELETE_USER_DATA": 'errors.INVALID_DELETE_USER_DATA',
    "INVALID_REGISTRATION_DATA": 'errors.INVALID_REGISTRATION_DATA',
    "LOGOUT_ERROR": 'errors.LOGOUT_ERROR',
    "BALANCE_DATA_ERROR": 'errors.BALANCE_DATA_ERROR',
    "BALANCE_DATA_NOT_FOUND": 'errors.BALANCE_DATA_NOT_FOUND',
    "BALANCE_DATA_RETRIEVAL_ERROR": 'errors.BALANCE_DATA_RETRIEVAL_ERROR',
    "INVALID_CHANGE_EMAIL_DATA": 'errors.INVALID_CHANGE_EMAIL_DATA',
    "INVALID_CHANGE_PASSWORD_DATA": 'errors.INVALID_CHANGE_PASSWORD_DATA',
    "PASSWORD_CHANGE_ERROR": 'errors.PASSWORD_CHANGE_ERROR',
    "PASSWORD_CHANGE_OTP_ERROR": 'errors.PASSWORD_CHANGE_OTP_ERROR',
    "PASSWORD_CHANGE_OTP_EXPIRED": 'errors.PASSWORD_CHANGE_OTP_EXPIRED',
    "PASSWORD_CHANGE_OTP_INVALID": 'errors.PASSWORD_CHANGE_OTP_INVALID',
    "PASSWORD_CHANGE_OTP_NOT_FOUND": 'errors.PASSWORD_CHANGE_OTP_NOT_FOUND',
    "INSUFFICIENT_LIQUIDITY_IN_TREASURY":
        'errors.INSUFFICIENT_LIQUIDITY_IN_TREASURY',
    "TOKEN_CONVERSION_ERROR": 'errors.TOKEN_CONVERSION_ERROR',
    "TOKEN_CONVERSION_ERROR_INVALID_ASSETS":
        'errors.TOKEN_CONVERSION_ERROR_INVALID_ASSETS',
    "TOKEN_CONVERSION_ERROR_SAME_ASSETS":
        'errors.TOKEN_CONVERSION_ERROR_SAME_ASSETS',
    "TOKEN_FCM_UPDATE_ERROR": 'errors.TOKEN_FCM_UPDATE_ERROR',
    "INVALID_RECOVERY_DATA": 'errors.INVALID_RECOVERY_DATA',
    "PASSWORD_RECOVERY_ERROR": 'errors.PASSWORD_RECOVERY_ERROR',
    "PASSWORD_RECOVERY_OTP_EXPIRED": 'errors.PASSWORD_RECOVERY_OTP_EXPIRED',
    "PASSWORD_RECOVERY_OTP_INVALID": 'errors.PASSWORD_RECOVERY_OTP_INVALID',
    "PASSWORD_RECOVERY_OTP_NOT_FOUND": 'errors.PASSWORD_RECOVERY_OTP_NOT_FOUND',
    "USER_NOT_FOUND": 'errors.USER_NOT_FOUND',
    "GENERAL_ERROR": 'errors.GENERAL_ERROR',
    "UNKNOWN_ERROR": 'errors.UNKNOWN_ERROR',
    "ACTIVE_LOAN_ERROR": 'errors.ACTIVE_LOAN_ERROR',
    "ALL_LOANS_ERROR": 'errors.ALL_LOANS_ERROR',
    "ASSET_NOT_FOUND": 'errors.ASSET_NOT_FOUND',
    "INSUFFICIENT_BALANCE": 'errors.INSUFFICIENT_BALANCE',
    "INSUFFICIENT_COLLATERAL": 'errors.INSUFFICIENT_COLLATERAL',
    "INVALID_LOAN_AMOUNT_DATA": 'errors.INVALID_LOAN_AMOUNT_DATA',
    "INVALID_LOAN_DATA": 'errors.INVALID_LOAN_DATA',
    "INVALID_PAYMENT_DATA": 'errors.INVALID_PAYMENT_DATA',
    "LIQUIDATION_HISTORY_ERROR": 'errors.LIQUIDATION_HISTORY_ERROR',
    "LOAN_ACCESS_DENIED": 'errors.LOAN_ACCESS_DENIED',
    "LOAN_CAPACITY_CALCULATION_ERROR": 'errors.LOAN_CAPACITY_CALCULATION_ERROR',
    "LOAN_CREATION_ERROR": 'errors.LOAN_CREATION_ERROR',
    "LOAN_DETAIL_ERROR": 'errors.LOAN_DETAIL_ERROR',
    "LOAN_LIQUIDATION_ERROR": 'errors.LOAN_LIQUIDATION_ERROR',
    "LOAN_NOT_FOUND": 'errors.LOAN_NOT_FOUND',
    "LOAN_TERMS_ERROR": 'errors.LOAN_TERMS_ERROR',
    "MISSING_LOAN_REFERENCE": 'errors.MISSING_LOAN_REFERENCE',
    "MISSING_PAYMENT_PROOF": 'errors.MISSING_PAYMENT_PROOF',
    "PAYMENT_CREATION_ERROR": 'errors.PAYMENT_CREATION_ERROR',
    "REQUIRED_TOKENS_CALCULATION_ERROR":
        'errors.REQUIRED_TOKENS_CALCULATION_ERROR',
    "USER_DEBT_STATUS_ERROR": 'errors.USER_DEBT_STATUS_ERROR',
    "USER_HAS_ACTIVE_LOAN": 'errors.USER_HAS_ACTIVE_LOAN',
    "USER_HAS_OVERDUE_DEBT": 'errors.USER_HAS_OVERDUE_DEBT',
    "VAULT_NOT_CONFIGURED": 'errors.VAULT_NOT_CONFIGURED',
    "INVALID_LOGIN_DATA": 'errors.INVALID_LOGIN_DATA',
    "LOGIN_EMAIL_NOT_VERIFIED": 'errors.LOGIN_EMAIL_NOT_VERIFIED',
    "LOGIN_ERROR": 'errors.LOGIN_ERROR',
    "LOGIN_WRONG_CREDENTIALS": 'errors.LOGIN_WRONG_CREDENTIALS',
    "INVALID_MINERAL_DATA": 'errors.INVALID_MINERAL_DATA',
    "MINERAL_CREATION_ERROR": 'errors.MINERAL_CREATION_ERROR',
    "MINERAL_DATA_RETRIEVAL_ERROR": 'errors.MINERAL_DATA_RETRIEVAL_ERROR',
    "ASSET_NOT_WITHDRAWABLE": 'errors.ASSET_NOT_WITHDRAWABLE',
    "INVALID_MINERAL_WITHDRAWAL_DATA": 'errors.INVALID_MINERAL_WITHDRAWAL_DATA',
    "MINERAL_WITHDRAWAL_CALCULATION_ERROR":
        'errors.MINERAL_WITHDRAWAL_CALCULATION_ERROR',
    "MINERAL_WITHDRAWAL_REQUEST_CREATION_ERROR":
        'errors.MINERAL_WITHDRAWAL_REQUEST_CREATION_ERROR',
    "MINERAL_WITHDRAWAL_REQUEST_DECISION_ERROR":
        'errors.MINERAL_WITHDRAWAL_REQUEST_DECISION_ERROR',
    "MINERAL_WITHDRAWAL_REQUEST_DECISION_NOT_QUOTED":
        'errors.MINERAL_WITHDRAWAL_REQUEST_DECISION_NOT_QUOTED',
    "MINERAL_WITHDRAWAL_REQUEST_DETAIL_ERROR":
        'errors.MINERAL_WITHDRAWAL_REQUEST_DETAIL_ERROR',
    "MINERAL_WITHDRAWAL_REQUEST_LIST_ERROR":
        'errors.MINERAL_WITHDRAWAL_REQUEST_LIST_ERROR',
    "MINERAL_WITHDRAWAL_REQUEST_NOT_FOUND":
        'errors.MINERAL_WITHDRAWAL_REQUEST_NOT_FOUND',
    "NOTIFICATIONS_RETRIEVAL_ERROR": 'errors.NOTIFICATIONS_RETRIEVAL_ERROR',
    "OFFRAMP_CALCULATION_ERROR": 'errors.OFFRAMP_CALCULATION_ERROR',
    "OFFRAMP_INSUFFICIENT_BALANCE": 'errors.OFFRAMP_INSUFFICIENT_BALANCE',
    "OFFRAMP_INVALID_ASSET": 'errors.OFFRAMP_INVALID_ASSET',
    "OFFRAMP_INVALID_DATA": 'errors.OFFRAMP_INVALID_DATA',
    "OFFRAMP_INVALID_PAYMENT_METHOD": 'errors.OFFRAMP_INVALID_PAYMENT_METHOD',
    "OFFRAMP_RATE_NOT_FOUND": 'errors.OFFRAMP_RATE_NOT_FOUND',
    "OFFRAMP_REQUEST_ERROR": 'errors.OFFRAMP_REQUEST_ERROR',
    "OFFRAMP_REQUEST_NOT_FOUND": 'errors.OFFRAMP_REQUEST_NOT_FOUND',
    "ONRAMP_CALCULATION_ERROR": 'errors.ONRAMP_CALCULATION_ERROR',
    "ONRAMP_INSUFFICIENT_TREASURY_TOKENS":
        'errors.ONRAMP_INSUFFICIENT_TREASURY_TOKENS',
    "ONRAMP_INVALID_ASSET": 'errors.ONRAMP_INVALID_ASSET',
    "ONRAMP_INVALID_DATA": 'errors.ONRAMP_INVALID_DATA',
    "ONRAMP_REQUEST_ERROR": 'errors.ONRAMP_REQUEST_ERROR',
    "ONRAMP_REQUEST_NOT_FOUND": 'errors.ONRAMP_REQUEST_NOT_FOUND',
    "INVALID_OTP_DATA": 'errors.INVALID_OTP_DATA',
    "OTP_ERROR": 'errors.OTP_ERROR',
    "OTP_INVALID": 'errors.OTP_INVALID',
    "ERROR_VALIDATING_PASSWORD": 'errors.ERROR_VALIDATING_PASSWORD',
    "INVALID_PASSWORD_DATA": 'errors.INVALID_PASSWORD_DATA',
    "PASSWORD_INVALID": 'errors.PASSWORD_INVALID',
    "PAYMENT_METHOD_BANK_LIST_ERROR": 'errors.PAYMENT_METHOD_BANK_LIST_ERROR',
    "PAYMENT_METHOD_BANK_NOT_FOUND": 'errors.PAYMENT_METHOD_BANK_NOT_FOUND',
    "PAYMENT_METHOD_CURRENCY_LIST_ERROR":
        'errors.PAYMENT_METHOD_CURRENCY_LIST_ERROR',
    "PAYMENT_METHOD_LIST_ERROR": 'errors.PAYMENT_METHOD_LIST_ERROR',
    "PAYMENT_METHOD_NOT_FOUND": 'errors.PAYMENT_METHOD_NOT_FOUND',
    "PAYMENT_METHOD_TYPE_LIST_ERROR": 'errors.PAYMENT_METHOD_TYPE_LIST_ERROR',
    "PROFILE_DATA_RETRIEVAL_ERROR": 'errors.PROFILE_DATA_RETRIEVAL_ERROR',
    "PROFILE_NOT_FOUND": 'errors.PROFILE_NOT_FOUND',
    "PROFILE_UPDATE_ERROR": 'errors.PROFILE_UPDATE_ERROR',
    "TOKEN_EXPIRED": 'errors.TOKEN_EXPIRED',
    "TOKEN_UNAUTHORIZED": 'errors.TOKEN_UNAUTHORIZED',
    "INVALID_DATE_FORMAT": 'errors.INVALID_DATE_FORMAT',
    "INVALID_PAGE_SIZE": 'errors.INVALID_PAGE_SIZE',
    "INVALID_QUOTATION_DATA": 'errors.INVALID_QUOTATION_DATA',
    "INVALID_STATUS_FILTER": 'errors.INVALID_STATUS_FILTER',
    "INVALID_TRANSACTION_DATA": 'errors.INVALID_TRANSACTION_DATA',
    "TRANSACTION_CREATION_ERROR": 'errors.TRANSACTION_CREATION_ERROR',
    "TRANSACTION_HISTORY_ERROR": 'errors.TRANSACTION_HISTORY_ERROR',
    "TRANSACTION_NOT_FOUND": 'errors.TRANSACTION_NOT_FOUND',
    "TRANSACTION_QUOTATION_ERROR": 'errors.TRANSACTION_QUOTATION_ERROR',
    "VERIFF_ATTEMPTS_EXCEEDED": 'errors.VERIFF_ATTEMPTS_EXCEEDED',
    "VERIFF_SESSION_CREATION_ERROR": 'errors.VERIFF_SESSION_CREATION_ERROR',
    "VERIFF_SESSION_UPDATE_ERROR": 'errors.VERIFF_SESSION_UPDATE_ERROR',
    "WAREHOUSE_CREATION_ERROR": 'errors.WAREHOUSE_CREATION_ERROR',
    "INVALID_WALLET_QUERY_PARAMS": 'errors.INVALID_WALLET_QUERY_PARAMS',
    "WALLET_ASSET_NOT_FOUND": 'errors.WALLET_ASSET_NOT_FOUND',
    "WALLET_NOT_FOUND": 'errors.WALLET_NOT_FOUND',
    "WALLET_VALIDATION_ERROR": 'errors.WALLET_VALIDATION_ERROR',
  };

  static String getErrorLabel(dynamic error) {
    if (error == null) return 'errors.unknown_error'.tr;

    if (error is List<dynamic>) {
      return getErrorLabel(error.firstOrNull);
    }

    final String errorKey = error.toString();
    final String? translationKey = knownErrors[errorKey]?.toString();

    print("${errorKey} ${translationKey?.tr}");

    if (translationKey != null) {
      return translationKey.tr;
    }

    return 'errors.unknown_error_with_key'.trParams({'key': errorKey});
  }
}
