import 'package:get/get.dart';

class AppSuccess {
  static const Map<String, dynamic> knownSuccess = {
    //? Loans
    "ACTIVE_LOAN_FOUND": "success.ACTIVE_LOAN_FOUND",
    "ALL_LOANS_FOUND": "success.ALL_LOANS_FOUND",

    //? Auth / Generic
    "AUTH0_EMAIL_UPDATED_SUCCESSFULLY":
        "success.AUTH0_EMAIL_UPDATED_SUCCESSFULLY",
    "AUTH_DATA_UPDATED": "success.AUTH_DATA_UPDATED",
    "EMAIL_AVAILABLE": "success.EMAIL_AVAILABLE",
    "EMAIL_UNAVAILABLE": "success.EMAIL_UNAVAILABLE",

    //? Balance
    "BALANCE_DATA_RETRIEVED": "success.BALANCE_DATA_RETRIEVED",

    //? General
    "LOGOUT_SUCCESS": "success.LOGOUT_SUCCESS",
    "SUCCESS": "success.SUCCESS",

    //? Loans (continued)
    "LIQUIDATION_HISTORY_FOUND": "success.LIQUIDATION_HISTORY_FOUND",
    "LOAN_CAPACITY_CALCULATED": "success.LOAN_CAPACITY_CALCULATED",
    "LOAN_CREATED_SUCCESSFULLY": "success.LOAN_CREATED_SUCCESSFULLY",
    "LOAN_DETAIL_FOUND": "success.LOAN_DETAIL_FOUND",
    "LOAN_LIQUIDATED_SUCCESSFULLY": "success.LOAN_LIQUIDATED_SUCCESSFULLY",
    "LOAN_TERMS_FOUND": "success.LOAN_TERMS_FOUND",
    "NO_ACTIVE_LOAN": "success.NO_ACTIVE_LOAN",
    "NO_LOANS_FOUND": "success.NO_LOANS_FOUND",

    //? Login
    "LOGIN_SUCCESS": "success.LOGIN_SUCCESS",

    //? Mineral Registry
    "MINERAL_CREATED": "success.MINERAL_CREATED",
    "MINERAL_DATA_RETRIEVED": "success.MINERAL_DATA_RETRIEVED",

    //? Mineral Withdrawal
    "MINERAL_WITHDRAWAL_CALCULATION_SUCCESS":
        "success.MINERAL_WITHDRAWAL_CALCULATION_SUCCESS",
    "MINERAL_WITHDRAWAL_REQUEST_CREATED":
        "success.MINERAL_WITHDRAWAL_REQUEST_CREATED",
    "MINERAL_WITHDRAWAL_REQUEST_DECISION_ACCEPTED":
        "success.MINERAL_WITHDRAWAL_REQUEST_DECISION_ACCEPTED",
    "MINERAL_WITHDRAWAL_REQUEST_DECISION_REJECTED":
        "success.MINERAL_WITHDRAWAL_REQUEST_DECISION_REJECTED",
    "MINERAL_WITHDRAWAL_REQUEST_DETAIL_SUCCESS":
        "success.MINERAL_WITHDRAWAL_REQUEST_DETAIL_SUCCESS",
    "MINERAL_WITHDRAWAL_REQUEST_LIST_EMPTY":
        "success.MINERAL_WITHDRAWAL_REQUEST_LIST_EMPTY",
    "MINERAL_WITHDRAWAL_REQUEST_LIST_SUCCESS":
        "success.MINERAL_WITHDRAWAL_REQUEST_LIST_SUCCESS",

    //? Notifications
    "NOTIFICATIONS_RETRIEVED": "success.NOTIFICATIONS_RETRIEVED",

    //? Off-Ramp (Venta)
    "OFFRAMP_CALCULATION_SUCCESS": "success.OFFRAMP_CALCULATION_SUCCESS",
    "OFFRAMP_REQUEST_APPROVED": "success.OFFRAMP_REQUEST_APPROVED",
    "OFFRAMP_REQUEST_CREATED": "success.OFFRAMP_REQUEST_CREATED",
    "OFFRAMP_REQUEST_PAID": "success.OFFRAMP_REQUEST_PAID",
    "OFFRAMP_REQUEST_REJECTED": "success.OFFRAMP_REQUEST_REJECTED",

    //? On-Ramp (Compra)
    "ONRAMP_CALCULATION_SUCCESS": "success.ONRAMP_CALCULATION_SUCCESS",
    "ONRAMP_PAYMENT_RECEIVED": "success.ONRAMP_PAYMENT_RECEIVED",
    "ONRAMP_REQUEST_COMPLETED": "success.ONRAMP_REQUEST_COMPLETED",
    "ONRAMP_REQUEST_CREATED": "success.ONRAMP_REQUEST_CREATED",
    "ONRAMP_REQUEST_REJECTED": "success.ONRAMP_REQUEST_REJECTED",

    //? OTP
    "OTP_SENT_SUCCESSFULLY": "success.OTP_SENT_SUCCESSFULLY",
    "OTP_VERIFIED_SUCCESSFULLY": "success.OTP_VERIFIED_SUCCESSFULLY",

    //? Password Change / Recovery
    "PASSWORD_CHANGED_SUCCESSFULLY": "success.PASSWORD_CHANGED_SUCCESSFULLY",
    "PASSWORD_CHANGE_COMPLETED": "success.PASSWORD_CHANGE_COMPLETED",
    "PASSWORD_CHANGE_OTP_REQUESTED": "success.PASSWORD_CHANGE_OTP_REQUESTED",
    "PASSWORD_CHANGE_OTP_VERIFIED": "success.PASSWORD_CHANGE_OTP_VERIFIED",
    "PASSWORD_RECOVERY_COMPLETED": "success.PASSWORD_RECOVERY_COMPLETED",
    "PASSWORD_RECOVERY_OTP_VERIFIED": "success.PASSWORD_RECOVERY_OTP_VERIFIED",
    "PASSWORD_RECOVERY_SENT": "success.PASSWORD_RECOVERY_SENT",
    "PASSWORD_VALID": "success.PASSWORD_VALID",

    //? Payments
    "PAYMENT_CREATED_SUCCESSFULLY": "success.PAYMENT_CREATED_SUCCESSFULLY",
    "PAYMENT_METHOD_BANK_LIST_SUCCESS":
        "success.PAYMENT_METHOD_BANK_LIST_SUCCESS",
    "PAYMENT_METHOD_CURRENCY_LIST_SUCCESS":
        "success.PAYMENT_METHOD_CURRENCY_LIST_SUCCESS",
    "PAYMENT_METHOD_LIST_SUCCESS": "success.PAYMENT_METHOD_LIST_SUCCESS",
    "PAYMENT_METHOD_TYPE_LIST_SUCCESS":
        "success.PAYMENT_METHOD_TYPE_LIST_SUCCESS",

    //? Profile
    "PROFILE_DATA_RETRIEVED": "success.PROFILE_DATA_RETRIEVED",
    "PROFILE_UPDATED": "success.PROFILE_UPDATED",

    //? Loans (continued)
    "REQUIRED_TOKENS_CALCULATED": "success.REQUIRED_TOKENS_CALCULATED",

    //? FCM Token
    "TOKEN_FCM_UPDATED": "success.TOKEN_FCM_UPDATED",

    //? Exchange
    "TOKEN_CONVERSION_SUCCESS": "success.TOKEN_CONVERSION_SUCCESS",
    "TOKEN_CONVERSION_SUCCESSFULLY_CALCULATED":
        "success.TOKEN_CONVERSION_SUCCESSFULLY_CALCULATED",

    //? Transactions
    "TRANSACTION_CREATED_SUCCESSFULLY":
        "success.TRANSACTION_CREATED_SUCCESSFULLY",
    "TRANSACTION_HISTORY_RETRIEVED": "success.TRANSACTION_HISTORY_RETRIEVED",
    "TRANSACTION_QUOTATION_CALCULATED":
        "success.TRANSACTION_QUOTATION_CALCULATED",
    "TRANSACTION_RETRIEVED": "success.TRANSACTION_RETRIEVED",

    //? User Management
    "USER_CREATED_SUCCESSFULLY": "success.USER_CREATED_SUCCESSFULLY",
    "USER_DELETED_FROM_AUTH0": "success.USER_DELETED_FROM_AUTH0",
    "USER_DELETED_FROM_LOCAL": "success.USER_DELETED_FROM_LOCAL",
    "USER_DELETED_SUCCESSFULLY": "success.USER_DELETED_SUCCESSFULLY",
    "USER_DEBT_STATUS_FOUND": "success.USER_DEBT_STATUS_FOUND",

    //? Veriff
    "VERIFF_SESSION_CREATED": "success.VERIFF_SESSION_CREATED",
    "VERIFF_SESSION_UPDATED": "success.VERIFF_SESSION_UPDATED",

    //? Wallet
    "WALLET_FOUND": "success.WALLET_FOUND",

    //? Warehouse
    "WAREHOUSE_CREATED": "success.WAREHOUSE_CREATED",
  };

  static String getSuccessLabel(dynamic success) {
    if (success == null) return 'success.process_completed'.tr;

    if (success is List<dynamic>) {
      return getSuccessLabel(success.firstOrNull);
    }

    final String successKey = success.toString();
    final String? translationKey = knownSuccess[successKey]?.toString();

    if (translationKey != null) {
      return translationKey.tr;
    }

    return 'success.process_completed'.tr;
  }
}
